// src/components/SelectField.vue
<template>
  <div class="sidebar-control">
    <div class="control-header">
      <div>
        <svgicon v-if="leftIcon" :name="leftIcon.icon" :width="leftIcon.width" :height="leftIcon.height" color="#FFFFFF"
                 :fill="false"></svgicon>
      </div>
      <div class="control-label">
        {{ label }}
      </div>
      <div>
        <svgicon v-if="rightIcon" :name="rightIcon.icon" :width="rightIcon.width" :height="rightIcon.height"
                 color="#FFFFFF" :fill="false"></svgicon>
      </div>
    </div>
    <div class="control-header">
      <select
        v-model="selectedOption"
        class="custom-select custom-select-sm custom-select-input"
        @change="onInput">
        <option
          v-for="(item, index) in options"
          :key="index"
          :value="item.value">
          {{ item.text }}
        </option>
      </select>
    </div>
  </div>
</template>

<script>
import '@/icons'

export default {
  name: 'SelectField',
  props: {
    leftIcon: {
      type: Object
    },
    rightIcon: {
      type: Object
    },
    label: {
      type: String,
      default: 'Label'
    },
    value: {
      type: String,
      default: ''
    },
    options: {
      type: Array,
      default: () => ([])
    }
  },
  data: () => ({
    selectedOption: ''
  }),
  watch: {
    value: function (newValue) {
      this.selectedOption = newValue
    }
  },
  mounted () {
    this.selectedOption = this.value
  },
  methods: {
    onInput ($event) {
      this.$emit('input', $event.target.value)
      this.selectedOption = $event.target.value
    }
  }
}
</script>

// src/components/SelectField.jsx
import React from 'react'
import SvgIcon from './SvgIcon'

const SelectField = ({
  leftIcon,
  rightIcon,
  label = 'Label',
  value = '',
  options = [],
  onChange
}) => {
  const handleInput = (e) => {
    onChange(e.target.value)
  }

  return (
    <div className="sidebar-control">
      <div className="control-header">
        <div>
          {leftIcon && (
            <SvgIcon
              name={leftIcon.icon}
              width={leftIcon.width}
              height={leftIcon.height}
              color="#FFFFFF"
              fill={false}
            />
          )}
        </div>
        <div className="control-label">{label}</div>
        <div>
          {rightIcon && (
            <SvgIcon
              name={rightIcon.icon}
              width={rightIcon.width}
              height={rightIcon.height}
              color="#FFFFFF"
              fill={false}
            />
          )}
        </div>
      </div>
      <div className="control-header">
        <select
          value={value}
          className="custom-select custom-select-sm custom-select-input"
          onChange={handleInput}
        >
          {options.map((item, index) => (
            <option key={index} value={item.value}>
              {item.text}
            </option>
          ))}
        </select>
      </div>
    </div>
  )
}

export default SelectField
