// src/components/Slider.jsx
import React from 'react'
import SvgIcon from './SvgIcon'

const Slider = ({
  disabled = false,
  leftIcon,
  rightIcon,
  min = 0,
  max = 100,
  step = 1,
  label = 'Label',
  value = 50,
  onChange
}) => {
  const handleInput = (e) => {
    const inputValue = parseFloat(e.target.value)
    if (inputValue > min) {
      onChange(inputValue)
    } else {
      onChange(min)
    }
  }

  return (
    <div className="sidebar-control">
      <div className="control-header">
        <div>
          {leftIcon && (
            <SvgIcon
              name={leftIcon.icon}
              width={leftIcon.width}
              height={leftIcon.height}
              color="#FFFFFF"
              fill={false}
            />
          )}
        </div>
        <div className="control-label">
          <div className="control-output">
            <input
              disabled={disabled}
              type="text"
              value={value}
              onChange={handleInput}
            />
          </div>
          {label}
        </div>
        <div>
          {rightIcon && (
            <SvgIcon
              name={rightIcon.icon}
              width={rightIcon.width}
              height={rightIcon.height}
              color="#FFFFFF"
              fill={false}
            />
          )}
        </div>
      </div>
      <input
        disabled={disabled}
        className="custom-range"
        type="range"
        min={min}
        max={max}
        step={step}
        value={value}
        onChange={handleInput}
      />
    </div>
  )
}

export default Slider

// src/components/Slider.vue
<template>
  <div class="sidebar-control">
    <div class="control-header">
      <div>
        <svgicon v-if="leftIcon" :name="leftIcon.icon" :width="leftIcon.width" :height="leftIcon.height" color="#FFFFFF" :fill="false"></svgicon>
      </div>
      <div class="control-label">
        <div class="control-output">
          <input :disabled="disabled" type="text" :value="value" @change="onInput">
        </div>{{ label }}
      </div>
      <div>
        <svgicon v-if="rightIcon" :name="rightIcon.icon" :width="rightIcon.width" :height="rightIcon.height" color="#FFFFFF" :fill="false"></svgicon>
      </div>
    </div>
    <input :disabled="disabled" class="custom-range" type="range" :min="min" :max="max" :step="step" :value="value" @input="onInput">
  </div>
</template>

<script>
import '@/icons'

export default {
  name: 'Slider',
  props: {
    disabled: {
      type: Boolean,
      default: false
    },
    leftIcon: {
      type: Object
    },
    rightIcon: {
      type: Object
    },
    min: {
      type: Number,
      default: 0
    },
    max: {
      type: Number,
      default: 100
    },
    step: {
      type: Number,
      default: 1
    },
    label: {
      type: String,
      default: 'Label'
    },
    value: {
      type: Number,
      default: 50
    }
  },
  methods: {
    onInput ($event) {
      if ($event.target.value > this.min) {
        this.$emit('input', $event.target.value)
      } else {
        this.$emit('input', this.min)
      }
      if ($event.target.value < this.min) {
        this.$emit('input', this.min)
      }
    }
  }
}
</script>
