// src/components/ColorPicker/ColorPicker.vue
<template>
  <div class="sidebar-control">
    <div class="control-header">
      <div class="custom-controls custom-switch" v-if="showToggle">
        <input :id="`${labelId}-toggle`" type="checkbox" class="custom-control-input" :value="toggleValue" :checked="!!toggleValue" @change="onToggle">
        <label class="custom-control-label" :for="`${labelId}-toggle`"></label>
      </div>
      <label :for="labelId" class="control-label color-control-label" :id="labelId">{{ label }}</label>
      <div class="color-indicator-wrapper">
        <div class="color-indicator" :style="{ 'background-color': `#${hex}` }" @click="toggleColorPicker"></div>
        <input :aria-labelledby="labelId"
               class="control-text-input color-control-text-input" type="text" :value="hex"
               @change="basicInputChange">
        <button class="btn btn-xsm btn-outline-secondary color-picker-button" @click.prevent="emitChange">SET</button>
      </div>
    </div>
    <transition name="slide">
      <div v-if="showColorPicker" role="application" aria-label="Color picker"
           class="mt-2"
           :class="['vc-sketch', disableAlpha ? 'vc-sketch__disable-alpha' : '']">
        <div class="vc-sketch-saturation-wrap">
          <saturation v-model="colors" @change="childChange"></saturation>
        </div>
        <div class="vc-sketch-controls">
          <div class="vc-sketch-sliders">
            <div class="vc-sketch-hue-wrap">
              <hue v-model="colors" @change="childChange"></hue>
            </div>
            <div class="vc-sketch-alpha-wrap" v-if="!disableAlpha">
              <alpha v-model="colors" @change="childChange"></alpha>
            </div>
          </div>
          <div class="vc-sketch-color-wrap">
            <div :aria-label="`Current color is ${activeColor}`" class="vc-sketch-active-color"
                 :style="{background: activeColor}"></div>
            <checkboard></checkboard>
          </div>
        </div>
        <div class="vc-sketch-field" v-if="!disableFields">
          <!-- rgba -->
          <div class="vc-sketch-field--double">
            <ed-in label="hex" :value="hex" @change="inputChange"></ed-in>
          </div>
          <div class="vc-sketch-field--single">
            <ed-in label="r" :value="colors.rgba.r" @change="inputChange"></ed-in>
          </div>
          <div class="vc-sketch-field--single">
            <ed-in label="g" :value="colors.rgba.g" @change="inputChange"></ed-in>
          </div>
          <div class="vc-sketch-field--single">
            <ed-in label="b" :value="colors.rgba.b" @change="inputChange"></ed-in>
          </div>
          <div class="vc-sketch-field--single" v-if="!disableAlpha">
            <ed-in label="a" :value="colors.a" :arrow-offset="0.01" :max="1" @change="inputChange"></ed-in>
          </div>
        </div>
        <div class="vc-sketch-presets" role="group"
             aria-label="A color preset, pick one to set as current color">
          <template v-for="c in presetColors">
            <div
              v-if="!isTransparent(c)"
              class="vc-sketch-presets-color"
              :aria-label="'Color:' + c"
              :key="c"
              :style="{background: c}"
              @click="handlePreset(c)">
            </div>
            <div
              v-else
              :key="c"
              :aria-label="'Color:' + c"
              class="vc-sketch-presets-color"
              @click="handlePreset(c)">
              <checkboard/>
            </div>
          </template>
        </div>
      </div>
    </transition>
  </div>
</template>

<script>
import colorMixin from './colorMixin'
import editableInput from './EditableInput.vue'
import saturation from './Saturation.vue'
import hue from './Hue.vue'
import alpha from './Alpha.vue'
import checkboard from './Checkboard.vue'

const presetColors = [
  '#D0021B', '#F5A623', '#F8E71C', '#8B572A', '#7ED321',
  '#417505', '#BD10E0', '#9013FE', '#4A90E2', '#50E3C2',
  '#B8E986', '#000000', '#4A4A4A', '#9B9B9B', '#CCCCCC',
  '#FFFFFF'
]

export default {
  name: 'ColorPicker',
  mixins: [colorMixin],
  data () {
    return {
      showColorPicker: false
    }
  },
  components: {
    saturation,
    hue,
    alpha,
    'ed-in': editableInput,
    checkboard
  },
  props: {
    showToggle: {
      type: Boolean,
      default: false
    },
    toggleValue: {
      type: Boolean,
      default: false
    },
    presetColors: {
      type: Array,
      default () {
        return presetColors
      }
    },
    disableAlpha: {
      type: Boolean,
      default: true
    },
    disableFields: {
      type: Boolean,
      default: false
    },
    label: {
      type: String,
      default: ''
    }
  },
  computed: {
    labelId () {
      return `input__label__color__${Math.random().toString().slice(2, 5)}`
    },
    hex () {
      let hex
      if (this.colors.a < 1) {
        hex = this.colors.hex8
      } else {
        hex = this.colors.hex
      }
      return hex.replace('#', '')
    },
    activeColor () {
      const rgba = this.colors.rgba
      return 'rgba(' + [rgba.r, rgba.g, rgba.b, rgba.a].join(',') + ')'
    }
  },
  methods: {
    onToggle ($event) {
      this.$emit('toggle', $event.target.checked)
    },
    toggleColorPicker () {
      this.showColorPicker = !this.showColorPicker
    },
    emitChange (e) {
      this.$emit('colorChange', `#${this.hex}`)
      this.showColorPicker = false
    },
    handlePreset (c) {
      this.colorChange({
        hex: c,
        source: 'hex'
      })
    },
    childChange (data) {
      this.colorChange(data)
    },
    basicInputChange (e) {
      this.isValidHex(e.target.value) && this.colorChange({
        hex: e.target.value,
        source: 'hex'
      })
      this.$emit('colorChange', `#${this.hex}`)
    },
    inputChange (data) {
      if (!data) {
        return
      }
      if (data.hex) {
        this.isValidHex(data.hex) && this.colorChange({
          hex: data.hex,
          source: 'hex'
        })
      } else if (data.r || data.g || data.b || data.a) {
        this.colorChange({
          r: data.r || this.colors.rgba.r,
          g: data.g || this.colors.rgba.g,
          b: data.b || this.colors.rgba.b,
          a: data.a || this.colors.rgba.a,
          source: 'rgba'
        })
      }
    }
  }
}
</script>

<style scoped>
  .vc-sketch {
    width: 100%;
    display: block;
    padding: 10px 10px 0;
    background: #fff;
    box-shadow: 0 0 0 1px rgba(0, 0, 0, .15), 0 8px 16px rgba(0, 0, 0, .15);
  }

  .vc-sketch-saturation-wrap {
    width: 100%;
    padding-bottom: 75%;
    position: relative;
    overflow: hidden;
  }

  .vc-sketch-controls {
    display: flex;
  }

  .vc-sketch-sliders {
    padding: 4px 0;
    flex: 1;
  }

  .vc-sketch-hue-wrap {
    position: relative;
    height: 20px;
  }

  .vc-sketch-alpha-wrap {
    position: relative;
    height: 10px;
    margin-top: 4px;
    overflow: hidden;
  }

  .vc-sketch-color-wrap {
    width: 24px;
    height: 24px;
    position: relative;
    margin-top: 4px;
    margin-left: 4px;
    border-radius: 3px;
  }

  .vc-sketch-active-color {
    position: absolute;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    border-radius: 2px;
    box-shadow: inset 0 0 0 1px rgba(0, 0, 0, .15), inset 0 0 4px rgba(0, 0, 0, .25);
    z-index: 2;
  }

  .vc-sketch-field {
    display: flex;
    padding-top: 4px;
  }

  .vc-sketch-field--single {
    flex: 1;
    padding-left: 6px;
  }

  .vc-sketch-field--double {
    flex: 2;
  }

  .vc-sketch-presets {
    margin-right: -10px;
    margin-left: -10px;
    padding-left: 10px;
    padding-top: 10px;
    border-top: 1px solid #eee;
  }

  .vc-sketch-presets-color {
    border-radius: 3px;
    overflow: hidden;
    position: relative;
    display: inline-block;
    margin: 0 10px 10px 0;
    vertical-align: top;
    cursor: pointer;
    width: 16px;
    height: 16px;
    box-shadow: inset 0 0 0 1px rgba(0, 0, 0, .15);
  }

  .vc-sketch__disable-alpha .vc-sketch-color-wrap {
    height: 20px;
  }

  .color-picker-wrapper {
    position: relative;
  }

  .color-control-label {
    margin-top: 2px;
    margin-bottom: 0;
    align-self: center;
    flex: 0 0 100px;
  }

  .color-picker-button, .color-indicator {
    margin-top: 5px;
  }

  .color-picker-button {
    margin-left: 10px;
  }

  .color-indicator {
    margin-top: 5px;
    width: 20px;
    height: 20px;
    background-color: red;
    display: block;
    position: relative;
  }

  .color-indicator-wrapper {
    position: relative;
    display: flex;
  }

  .color-control-text-input {
    display: inline-block;
    width: 70px;
  }
</style>

// src/components/ColorPicker/ColorPicker.jsx
import React, { useState, useEffect } from 'react'
import { colorChange, isValidHex, isTransparent } from './colorUtils'
import EditableInput from './EditableInput'
import Saturation from './Saturation'
import Hue from './Hue'
import Alpha from './Alpha'
import Checkboard from './Checkboard'
import './ColorPicker.scss'

const presetColors = [
  '#D0021B', '#F5A623', '#F8E71C', '#8B572A', '#7ED321',
  '#417505', '#BD10E0', '#9013FE', '#4A90E2', '#50E3C2',
  '#B8E986', '#000000', '#4A4A4A', '#9B9B9B', '#CCCCCC',
  '#FFFFFF'
]

const ColorPicker = ({
  value,
  showToggle = false,
  toggleValue = false,
  disableAlpha = true,
  disableFields = false,
  label = '',
  onToggle,
  onColorChange
}) => {
  const [colors, setColors] = useState(colorChange(value))
  const [showColorPicker, setShowColorPicker] = useState(false)
  const [oldHue, setOldHue] = useState(0)

  useEffect(() => {
    setColors(colorChange(value))
  }, [value])

  const handleColorChange = (data) => {
    const newColors = colorChange(data, oldHue || colors.hsl.h)
    setOldHue(newColors.hsl.h)
    setColors(newColors)
  }

  const hex = colors.a < 1 ? colors.hex8.replace('#', '') : colors.hex.replace('#', '')
  const activeColor = `rgba(${colors.rgba.r},${colors.rgba.g},${colors.rgba.b},${colors.rgba.a})`
  const labelId = `input__label__color__${Math.random().toString().slice(2, 5)}`

  const handleToggle = (e) => {
    onToggle && onToggle(e.target.checked)
    onColorChange && onColorChange(`#${hex}`)
  }

  const toggleColorPicker = () => {
    setShowColorPicker(!showColorPicker)
  }

  const emitChange = () => {
    onColorChange && onColorChange(`#${hex}`)
    setShowColorPicker(false)
  }

  const handlePreset = (c) => {
    handleColorChange({
      hex: c,
      source: 'hex'
    })
  }

  const basicInputChange = (e) => {
    if (isValidHex(e.target.value)) {
      handleColorChange({
        hex: e.target.value,
        source: 'hex'
      })
    }
    onColorChange && onColorChange(`#${hex}`)
  }

  const inputChange = (data) => {
    if (!data) {
      return
    }
    if (data.hex) {
      if (isValidHex(data.hex)) {
        handleColorChange({
          hex: data.hex,
          source: 'hex'
        })
      }
    } else if (data.r || data.g || data.b || data.a) {
      handleColorChange({
        r: data.r || colors.rgba.r,
        g: data.g || colors.rgba.g,
        b: data.b || colors.rgba.b,
        a: data.a || colors.rgba.a,
        source: 'rgba'
      })
    }
  }

  return (
    <div className="sidebar-control">
      <div className="control-header">
        {showToggle && (
          <div className="custom-controls custom-switch">
            <input
              id={`${labelId}-toggle`}
              type="checkbox"
              className="custom-control-input"
              value={toggleValue}
              checked={!!toggleValue}
              onChange={handleToggle}
            />
            <label className="custom-control-label" htmlFor={`${labelId}-toggle`}></label>
          </div>
        )}
        <label htmlFor={labelId} className="control-label color-control-label" id={labelId}>
          {label}
        </label>
        <div className="color-indicator-wrapper">
          <div
            className="color-indicator"
            style={{ backgroundColor: `#${hex}` }}
            onClick={toggleColorPicker}
          ></div>
          <input
            aria-labelledby={labelId}
            className="control-text-input color-control-text-input"
            type="text"
            value={hex}
            onChange={basicInputChange}
          />
          <button className="btn btn-xsm btn-outline-secondary color-picker-button" onClick={emitChange}>
            SET
          </button>
        </div>
      </div>
      {showColorPicker && (
        <div
          role="application"
          aria-label="Color picker"
          className={`mt-2 vc-sketch ${disableAlpha ? 'vc-sketch__disable-alpha' : ''}`}
        >
          <div className="vc-sketch-saturation-wrap">
            <Saturation value={colors} onChange={handleColorChange} />
          </div>
          <div className="vc-sketch-controls">
            <div className="vc-sketch-sliders">
              <div className="vc-sketch-hue-wrap">
                <Hue value={colors} onChange={handleColorChange} />
              </div>
              {!disableAlpha && (
                <div className="vc-sketch-alpha-wrap">
                  <Alpha value={colors} onChange={handleColorChange} />
                </div>
              )}
            </div>
            <div className="vc-sketch-color-wrap">
              <div
                aria-label={`Current color is ${activeColor}`}
                className="vc-sketch-active-color"
                style={{ background: activeColor }}
              ></div>
              <Checkboard />
            </div>
          </div>
          {!disableFields && (
            <div className="vc-sketch-field">
              <div className="vc-sketch-field--double">
                <EditableInput label="hex" value={hex} onChange={inputChange} />
              </div>
              <div className="vc-sketch-field--single">
                <EditableInput label="r" value={colors.rgba.r} onChange={inputChange} />
              </div>
              <div className="vc-sketch-field--single">
                <EditableInput label="g" value={colors.rgba.g} onChange={inputChange} />
              </div>
              <div className="vc-sketch-field--single">
                <EditableInput label="b" value={colors.rgba.b} onChange={inputChange} />
              </div>
              {!disableAlpha && (
                <div className="vc-sketch-field--single">
                  <EditableInput label="a" value={colors.a} arrowOffset={0.01} max={1} onChange={inputChange} />
                </div>
              )}
            </div>
          )}
          <div className="vc-sketch-presets" role="group" aria-label="A color preset, pick one to set as current color">
            {presetColors.map((c) => (
              !isTransparent(c) ? (
                <div
                  key={c}
                  className="vc-sketch-presets-color"
                  aria-label={'Color:' + c}
                  style={{ background: c }}
                  onClick={() => handlePreset(c)}
                ></div>
              ) : (
                <div
                  key={c}
                  aria-label={'Color:' + c}
                  className="vc-sketch-presets-color"
                  onClick={() => handlePreset(c)}
                >
                  <Checkboard />
                </div>
              )
            ))}
          </div>
        </div>
      )}
    </div>
  )
}

export default ColorPicker
