// src/components/ColorPicker/EditableInput.jsx
import React, { useState, useEffect, useRef } from 'react'
import './EditableInput.scss'

const EditableInput = ({
  label,
  labelText,
  desc,
  value,
  max,
  min,
  arrowOffset = 1,
  onChange
}) => {
  const [val, setVal] = useState(value)
  const inputRef = useRef(null)

  useEffect(() => {
    setVal(value)
  }, [value])

  const handleChange = (newVal) => {
    let data = {}
    data[label] = newVal
    if (data.hex === undefined && data['#'] === undefined) {
      onChange(data)
    } else if (newVal.length > 5) {
      onChange(data)
    }
  }

  const handleInput = (e) => {
    const inputValue = e.target.value
    if (!(max === undefined) && +inputValue > max) {
      if (inputRef.current) {
        inputRef.current.value = max
      }
      setVal(max)
    } else {
      setVal(inputValue)
    }
  }

  const handleUpdate = (e) => {
    handleChange(e.target.value)
  }

  const handleKeyDown = (e) => {
    let currentVal = val
    let number = Number(currentVal)

    if (number) {
      let amount = arrowOffset || 1

      // Up
      if (e.keyCode === 38) {
        currentVal = number + amount
        handleChange(currentVal)
        e.preventDefault()
      }

      // Down
      if (e.keyCode === 40) {
        currentVal = number - amount
        handleChange(currentVal)
        e.preventDefault()
      }
    }
  }

  const labelId = `input__label__${label}__${Math.random().toString().slice(2, 5)}`
  const labelSpanText = labelText || label

  return (
    <div className="vc-editable-input">
      <input
        aria-labelledby={labelId}
        className="vc-input__input"
        value={val}
        onChange={handleInput}
        onKeyDown={handleKeyDown}
        onBlur={handleUpdate}
        ref={inputRef}
      />
      <span htmlFor={label} className="vc-input__label" id={labelId}>
        {labelSpanText}
      </span>
      <span className="vc-input__desc">{desc}</span>
    </div>
  )
}

export default EditableInput

// src/components/ColorPicker/EditableInput.vue
<template>
  <div class="vc-editable-input">
    <input
      :aria-labelledby="labelId"
      class="vc-input__input"
      v-model="val"
      @keydown="handleKeyDown"
      @input="update"
      ref="input"
    >
    <span :for="label" class="vc-input__label" :id="labelId">{{labelSpanText}}</span>
    <span class="vc-input__desc">{{desc}}</span>
  </div>
</template>

<script>
export default {
  name: 'editableInput',
  props: {
    label: String,
    labelText: String,
    desc: String,
    value: [String, Number],
    max: Number,
    min: Number,
    arrowOffset: {
      type: Number,
      default: 1
    }
  },
  computed: {
    val: {
      get () {
        return this.value
      },
      set (v) {
        // TODO: min
        if (!(this.max === undefined) && +v > this.max) {
          this.$refs.input.value = this.max
        } else {
          return v
        }
      }
    },
    labelId () {
      return `input__label__${this.label}__${Math.random().toString().slice(2, 5)}`
    },
    labelSpanText () {
      return this.labelText || this.label
    }
  },
  methods: {
    update (e) {
      this.handleChange(e.target.value)
    },
    handleChange (newVal) {
      let data = {}
      data[this.label] = newVal
      if (data.hex === undefined && data['#'] === undefined) {
        this.$emit('change', data)
      } else if (newVal.length > 5) {
        this.$emit('change', data)
      }
    },
    // **** unused
    // handleBlur (e) {
    //   console.log(e)
    // },
    handleKeyDown (e) {
      let val = this.val
      let number = Number(val)

      if (number) {
        let amount = this.arrowOffset || 1

        // Up
        if (e.keyCode === 38) {
          val = number + amount
          this.handleChange(val)
          e.preventDefault()
        }

        // Down
        if (e.keyCode === 40) {
          val = number - amount
          this.handleChange(val)
          e.preventDefault()
        }
      }
    }
    // **** unused
    // handleDrag (e) {
    //   console.log(e)
    // },
    // handleMouseDown (e) {
    //   console.log(e)
    // }
  }
}
</script>

<style scoped>
.vc-editable-input {
  position: relative;
}
.vc-input__input {
  font-family: SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace;
  border: 0;
  outline: none;
  width: 90%;
  padding: 4px 0 3px 10%;
  border: none;
  box-shadow: inset 0 0 0 1px #ccc;
  font-size: 10px;
}
.vc-input__label {
  display: block;
  text-align: center;
  font-size: 11px;
  color: #222;
  padding-top: 3px;
  padding-bottom: 4px;
  text-transform: capitalize;
}
</style>
